name: rbws_frykman
description: The web server for my personal website, frykman.dev.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  rbws: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
